### ISSUE TITLE
about `MPI_Allreduce` in updateOctreeGlobalGpu

### ISSUE THREAD

**Issue by UnlimitedR** [sebkelle1/cornerstone-octree#27]
in this line `MPI_Allreduce(counts.data(), counts_reduced.data(), counts.size(), MPI_UNSIGNED, MPI_SUM, MPI_COMM_WORLD);` in /include/cstone/tree/update_mpi_gpu.cuh, is `counts.size()` different among different ranks? it looks so to me.

**Comment by sekelle** [comment]
Hi, `counts.size()` is identical on all ranks. The function you mention here is for building globally replicated octrees, i.e. the resulting tree is identical on all ranks (and the `MPI_Allreduce` wouldn't work otherwise).
