### ISSUE TITLE
failed to complie on windows10

### ISSUE THREAD

**Issue by leonjang** [sebkelle1/cornerstone-octree#32]
-- Configuring done (30.2s)
-- Generating done (0.1s)
-- Build files have been written to: C:/dev/cornerstone-octree-unchange/cmake-build-debug

Cannot get compiler information:
Compiler exited with error code 2: "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.42.34433\bin\Hostx64\x64\cl.exe" @C:\Users\shonCloud\AppData\Local\Temp\response-file16835164717224326042 C:\Users\shonCloud\AppData\Local\Temp\compiler-file14524580473862131358 | @response-file16835164717224326042=/TP /DWIN32 /D_WINDOWS /EHsc /Zi /Ob0 /Od /RTC1 -std:c++20 -MDd -Wno-unknown-pragmas /Be /Bd /E /w /wd4067
用于 x64 的 Microsoft (R) C/C++ 优化编译器 19.42.34433 版
版权所有(C) Microsoft Corporation。保留所有权利。
	
all:
		@cd C:\dev\cornerstone-octree-unchange\cmake-build-debug\test\coord_samples
		@set INCLUDE=C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.42.34433\include;C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\VS\include;C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt;C:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\um;C:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\shared;C:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\winrt;C:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\cppwinrt
		@set LIB=C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.42.34433\lib\x64;C:\Program Files (x86)\Windows Kits\10\lib\10.0.22621.0\ucrt\x64;C:\Program Files (x86)\Windows Kits\10\\lib\10.0.22621.0\\um\x64
		@set LIBPATH=C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.42.34433\lib\x64;C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.42.34433\lib\x86\store\references;C:\Program Files (x86)\Windows Kits\10\UnionMetadata\10.0.22621.0;C:\Program Files (x86)\Windows Kits\10\References\10.0.22621.0;C:\Windows\Microsoft.NET\Framework64\v4.0.30319
		@set CL=
		@set _CL_=
		@set LINK=
		C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.42.34433\bin\Hostx64\x64\cl.exe @<< C:\Users\shonCloud\AppData\Local\Temp\compiler-file14524580473862131358
	/TP /DWIN32 /D_WINDOWS /EHsc /Zi /Ob0 /Od /RTC1 -std:c++20 -MDd -Wno-unknown-pragmas /Be /Bd /E /w /wd4067<<
	
cl /TP /DWIN32 /D_WINDOWS /EHsc /Zi /Ob0 /Od /RTC1 -std:c++20 -MDd -Wno-unknown-pragmas /Be /Bd /E /w /wd4067
cl: 命令行 error D8021 :无效的数值参数“/Wno-unknown-pragmas”
	
	
Compiler exited with error code 2: "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.42.34433\bin\Hostx64\x64\cl.exe" @C:\Users\shonCloud\AppData\Local\Temp\response-file3517486233097798769 C:\Users\shonCloud\AppData\Local\Temp\compiler-file14524580473862131358 | @response-file3517486233097798769=/TP /DWIN32 /D_WINDOWS /EHsc /Zi /Ob0 /Od /RTC1 -std:c++20 -MDd -Wall -Wextra -Wno-unknown-pragmas /Be /Bd /E /w /wd4067
用于 x64 的 Microsoft (R) C/C++ 优化编译器 19.42.34433 版
版权所有(C) Microsoft Corporation。保留所有权利。
	
all:
		@cd C:\dev\cornerstone-octree-unchange\cmake-build-debug\test\unit
		@set INCLUDE=C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.42.34433\include;C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\VS\include;C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt;C:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\um;C:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\shared;C:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\winrt;C:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\cppwinrt
		@set LIB=C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.42.34433\lib\x64;C:\Program Files (x86)\Windows Kits\10\lib\10.0.22621.0\ucrt\x64;C:\Program Files (x86)\Windows Kits\10\\lib\10.0.22621.0\\um\x64
		@set LIBPATH=C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.42.34433\lib\x64;C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.42.34433\lib\x86\store\references;C:\Program Files (x86)\Windows Kits\10\UnionMetadata\10.0.22621.0;C:\Program Files (x86)\Windows Kits\10\References\10.0.22621.0;C:\Windows\Microsoft.NET\Framework64\v4.0.30319
		@set CL=
		@set _CL_=
		@set LINK=
		C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.42.34433\bin\Hostx64\x64\cl.exe @<< C:\Users\shonCloud\AppData\Local\Temp\compiler-file14524580473862131358
	/TP /DWIN32 /D_WINDOWS /EHsc /Zi /Ob0 /Od /RTC1 -std:c++20 -MDd -Wall -Wextra -Wno-unknown-pragmas /Be /Bd /E /w /wd4067<<
	
cl /TP /DWIN32 /D_WINDOWS /EHsc /Zi /Ob0 /Od /RTC1 -std:c++20 -MDd -Wall -Wextra -Wno-unknown-pragmas /Be /Bd /E /w /wd4067
cl: 命令行 error D8021 :无效的数值参数“/Wextra”
	
	

[Failed to reload]

**Comment by sekelle** [comment]
The error message says that CMake failed to configure the project, because CMake didn't recognize the compiler, i.e. it didn't even get to try compiling Cornerstone octree.

Perhaps you could try to compile a minimal CMake/C++ project, something like "Hello world"?

**Comment by leonjang** [comment]
after i comment out all the param "-Wno....",  cmake reload was find.
#target_compile_options(${exename} PRIVATE -Wno-unknown-pragmas)

![image](https://github.com/user-attachments/assets/062a4238-e150-4215-a374-219be66ee300)

but project can't be built :
C:\dev\cornerstone-octree-unchange\include\cstone/util/array.hpp(69): error: namespace "std" has no member "reverse_iterator"
      typedef std::reverse_iterator<iterator> reverse_iterator;
                   ^
                   
 C:\dev\cornerstone-octree-unchange\include\cstone\primitives\clz.hpp(133): error C3861: “__builtin_ctz”:
 
 
![image](https://github.com/user-attachments/assets/c8711812-d8c2-4fca-8139-ee8736c1e047)

                   
 worked really find on my ubuntu machine.
